export const predefinedThemes = [
  {
    name: 'Modern Blue',
    colors: {
      primary: '#2563eb',
      secondary: '#7c3aed',
      accent: '#06b6d4',
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#1f2937',
      textSecondary: '#6b7280',
      border: '#e5e7eb',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingFont: 'Inter, system-ui, sans-serif',
      fontSize: {
        small: '0.875rem',
        base: '1rem',
        large: '1.125rem',
        xl: '1.25rem',
        xxl: '1.5rem',
      },
    },
    layout: {
      containerMaxWidth: '1200px',
      borderRadius: {
        small: '0.25rem',
        medium: '0.5rem',
        large: '0.75rem',
        xl: '1rem',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        xxl: '3rem',
      },
      shadows: {
        small: '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
        medium: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
        large: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      },
      grid: {
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
          large: 4,
        },
        gap: '1rem',
      },
      header: {
        height: '4rem',
        sticky: true,
        blur: false,
      },
      buttons: {
        size: {
          small: { height: '2rem', padding: '0.5rem 0.75rem', fontSize: '0.875rem' },
          medium: { height: '2.5rem', padding: '0.625rem 1rem', fontSize: '1rem' },
          large: { height: '3rem', padding: '0.75rem 1.25rem', fontSize: '1.125rem' },
        },
        style: 'rounded',
      },
      cards: {
        padding: '1.5rem',
        borderWidth: '1px',
        hoverEffect: 'lift',
      },
    },
  },
  {
    name: 'Dark Mode',
    colors: {
      primary: '#3b82f6',
      secondary: '#8b5cf6',
      accent: '#06b6d4',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      textSecondary: '#cbd5e1',
      border: '#334155',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingFont: 'Inter, system-ui, sans-serif',
      fontSize: {
        small: '0.875rem',
        base: '1rem',
        large: '1.125rem',
        xl: '1.25rem',
        xxl: '1.5rem',
      },
    },
    layout: {
      containerMaxWidth: '1200px',
      borderRadius: {
        small: '0.5rem',
        medium: '0.75rem',
        large: '1rem',
        xl: '1.25rem',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        xxl: '3rem',
      },
      shadows: {
        small: '0 2px 4px 0 rgba(0, 0, 0, 0.2)',
        medium: '0 6px 8px -1px rgba(0, 0, 0, 0.2)',
        large: '0 12px 16px -3px rgba(0, 0, 0, 0.2)',
        xl: '0 24px 28px -5px rgba(0, 0, 0, 0.2)',
      },
      grid: {
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
          large: 4,
        },
        gap: '1rem',
      },
      header: {
        height: '4rem',
        sticky: true,
        blur: true,
      },
      buttons: {
        size: {
          small: { height: '2rem', padding: '0.5rem 0.75rem', fontSize: '0.875rem' },
          medium: { height: '2.5rem', padding: '0.625rem 1rem', fontSize: '1rem' },
          large: { height: '3rem', padding: '0.75rem 1.25rem', fontSize: '1.125rem' },
        },
        style: 'rounded',
      },
      cards: {
        padding: '1.5rem',
        borderWidth: '1px',
        hoverEffect: 'glow',
      },
    },
  },
  {
    name: 'Warm Orange',
    colors: {
      primary: '#ea580c',
      secondary: '#dc2626',
      accent: '#f59e0b',
      background: '#fffbeb',
      surface: '#fef3c7',
      text: '#92400e',
      textSecondary: '#b45309',
      border: '#fbbf24',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    typography: {
      fontFamily: 'Poppins, system-ui, sans-serif',
      headingFont: 'Poppins, system-ui, sans-serif',
      fontSize: {
        small: '0.875rem',
        base: '1rem',
        large: '1.125rem',
        xl: '1.25rem',
        xxl: '1.5rem',
      },
    },
    layout: {
      containerMaxWidth: '1200px',
      borderRadius: {
        small: '0.75rem',
        medium: '1rem',
        large: '1.5rem',
        xl: '2rem',
      },
      spacing: {
        xs: '0.5rem',
        sm: '0.75rem',
        md: '1.25rem',
        lg: '1.75rem',
        xl: '2.5rem',
        xxl: '3.5rem',
      },
      shadows: {
        small: '0 2px 8px 0 rgba(234, 88, 12, 0.1)',
        medium: '0 6px 12px -1px rgba(234, 88, 12, 0.15)',
        large: '0 12px 20px -3px rgba(234, 88, 12, 0.2)',
        xl: '0 24px 32px -5px rgba(234, 88, 12, 0.25)',
      },
      grid: {
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 2,
          large: 3,
        },
        gap: '1.5rem',
      },
      header: {
        height: '5rem',
        sticky: true,
        blur: false,
      },
      buttons: {
        size: {
          small: { height: '2.25rem', padding: '0.625rem 1rem', fontSize: '0.875rem' },
          medium: { height: '2.75rem', padding: '0.75rem 1.25rem', fontSize: '1rem' },
          large: { height: '3.25rem', padding: '1rem 1.5rem', fontSize: '1.125rem' },
        },
        style: 'pill',
      },
      cards: {
        padding: '2rem',
        borderWidth: '2px',
        hoverEffect: 'scale',
      },
    },
  },
  {
    name: 'Forest Green',
    colors: {
      primary: '#059669',
      secondary: '#0d9488',
      accent: '#84cc16',
      background: '#f0fdf4',
      surface: '#dcfce7',
      text: '#064e3b',
      textSecondary: '#065f46',
      border: '#86efac',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    typography: {
      fontFamily: 'Nunito, system-ui, sans-serif',
      headingFont: 'Nunito, system-ui, sans-serif',
      fontSize: {
        small: '0.875rem',
        base: '1rem',
        large: '1.125rem',
        xl: '1.25rem',
        xxl: '1.5rem',
      },
    },
    layout: {
      containerMaxWidth: '1100px',
      borderRadius: {
        small: '0.25rem',
        medium: '0.375rem',
        large: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        xxl: '2.5rem',
      },
      shadows: {
        small: '0 1px 3px 0 rgba(5, 150, 105, 0.1)',
        medium: '0 4px 6px -1px rgba(5, 150, 105, 0.1)',
        large: '0 10px 15px -3px rgba(5, 150, 105, 0.15)',
        xl: '0 20px 25px -5px rgba(5, 150, 105, 0.2)',
      },
      grid: {
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
          large: 4,
        },
        gap: '1rem',
      },
      header: {
        height: '3.5rem',
        sticky: false,
        blur: false,
      },
      buttons: {
        size: {
          small: { height: '1.875rem', padding: '0.375rem 0.75rem', fontSize: '0.875rem' },
          medium: { height: '2.25rem', padding: '0.5rem 1rem', fontSize: '1rem' },
          large: { height: '2.75rem', padding: '0.75rem 1.25rem', fontSize: '1.125rem' },
        },
        style: 'sharp',
      },
      cards: {
        padding: '1.25rem',
        borderWidth: '1px',
        hoverEffect: 'lift',
      },
    },
  },
  {
    name: 'Purple Gradient',
    colors: {
      primary: '#8b5cf6',
      secondary: '#a855f7',
      accent: '#ec4899',
      background: '#faf5ff',
      surface: '#f3e8ff',
      text: '#581c87',
      textSecondary: '#7c3aed',
      border: '#c4b5fd',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    typography: {
      fontFamily: 'Lato, system-ui, sans-serif',
      headingFont: 'Playfair Display, serif',
      fontSize: {
        small: '0.875rem',
        base: '1rem',
        large: '1.125rem',
        xl: '1.25rem',
        xxl: '1.625rem',
      },
    },
    layout: {
      containerMaxWidth: '1300px',
      borderRadius: {
        small: '0.375rem',
        medium: '0.625rem',
        large: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        xs: '0.375rem',
        sm: '0.625rem',
        md: '1.125rem',
        lg: '1.625rem',
        xl: '2.25rem',
        xxl: '3.25rem',
      },
      shadows: {
        small: '0 2px 6px 0 rgba(139, 92, 246, 0.15)',
        medium: '0 6px 10px -1px rgba(139, 92, 246, 0.2)',
        large: '0 12px 18px -3px rgba(139, 92, 246, 0.25)',
        xl: '0 24px 30px -5px rgba(139, 92, 246, 0.3)',
      },
      grid: {
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
          large: 3,
        },
        gap: '1.25rem',
      },
      header: {
        height: '4.5rem',
        sticky: true,
        blur: true,
      },
      buttons: {
        size: {
          small: { height: '2.125rem', padding: '0.5rem 0.875rem', fontSize: '0.875rem' },
          medium: { height: '2.625rem', padding: '0.75rem 1.125rem', fontSize: '1rem' },
          large: { height: '3.125rem', padding: '1rem 1.375rem', fontSize: '1.125rem' },
        },
        style: 'rounded',
      },
      cards: {
        padding: '1.75rem',
        borderWidth: '1px',
        hoverEffect: 'glow',
      },
    },
  },
  {
    name: 'Minimalist',
    colors: {
      primary: '#000000',
      secondary: '#374151',
      accent: '#6b7280',
      background: '#ffffff',
      surface: '#f9fafb',
      text: '#111827',
      textSecondary: '#6b7280',
      border: '#d1d5db',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
    },
    typography: {
      fontFamily: 'system-ui, sans-serif',
      headingFont: 'system-ui, sans-serif',
      fontSize: {
        small: '0.875rem',
        base: '1rem',
        large: '1.125rem',
        xl: '1.25rem',
        xxl: '1.5rem',
      },
    },
    layout: {
      containerMaxWidth: '1024px',
      borderRadius: {
        small: '0rem',
        medium: '0.25rem',
        large: '0.375rem',
        xl: '0.5rem',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        xxl: '2.5rem',
      },
      shadows: {
        small: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        medium: '0 2px 4px -1px rgba(0, 0, 0, 0.1)',
        large: '0 4px 6px -2px rgba(0, 0, 0, 0.1)',
        xl: '0 8px 12px -4px rgba(0, 0, 0, 0.15)',
      },
      grid: {
        columns: {
          mobile: 1,
          tablet: 2,
          desktop: 3,
          large: 4,
        },
        gap: '1rem',
      },
      header: {
        height: '3.5rem',
        sticky: false,
        blur: false,
      },
      buttons: {
        size: {
          small: { height: '1.75rem', padding: '0.25rem 0.5rem', fontSize: '0.875rem' },
          medium: { height: '2rem', padding: '0.5rem 0.75rem', fontSize: '1rem' },
          large: { height: '2.5rem', padding: '0.75rem 1rem', fontSize: '1.125rem' },
        },
        style: 'sharp',
      },
      cards: {
        padding: '1rem',
        borderWidth: '1px',
        hoverEffect: 'none',
      },
    },
  },
];
